import { writeFileSync } from 'fs';
import matter from 'gray-matter';
import { readCreatedTimestamp, humanizeLabel } from './preservation.js';
import type { Chunk } from '../chunking/types.js';
import type { Config } from '../config.js';

export interface LlmPageContent {
  frontmatter: Record<string, unknown>;
  body: string;
}

export function buildDocumentPage(
  chunk: Chunk,
  config: Config,
  entityTitles: string[] = [],
  topicTitles: string[] = [],
): LlmPageContent {
  const confidence = deriveConfidence(chunk);
  const source = chunk.sources[0];
  const sourceFileName = source?.file ? pathBasename(source.file) : '';
  const sourceTitle = sourceFileName ? `Source: ${sourceFileName}` : '';
  const indexTitle = `${config.wiki.title} Index`;
  const now = new Date().toISOString();

  const frontmatter = {
    title: chunk.title,
    created: now,
    updated: now,
    type: 'document',
    wiki: config.wiki.slug,
    tags: chunk.tags,
    confidence,
    below_min: chunk.belowMin,
    char_count: chunk.charCount,
    boundary_type: chunk.boundaryType,
    sources: chunk.sources.map((source) => ({
      id: source.id,
      file: source.file,
      pages: source.pages,
      extracted: source.extracted,
      label: humanizeLabel(pathBasename(source.file)),
    })),
  };

  const sourceCitations: string[] = chunk.sources.map((source) => {
    return `- [^${source.id}]: ${source.file}, pages ${source.pages}`;
  });

  const wikilinks: string[] = [indexTitle];
  if (sourceTitle) {
    wikilinks.push(sourceTitle);
  }

  // Add resolved entity/topic links whose content appears in the chunk.
  const contentLower = chunk.content.toLowerCase();
  for (const title of entityTitles.sort((a, b) => b.length - a.length)) {
    const name = title.replace(/^Entity: /, '').toLowerCase();
    if (contentLower.includes(name)) {
      wikilinks.push(title);
    }
  }
  for (const title of topicTitles.sort((a, b) => b.length - a.length)) {
    const name = title.replace(/^Topic: /, '').toLowerCase();
    if (contentLower.includes(name)) {
      wikilinks.push(title);
    }
  }

  const bodyLines = [
    `# ${chunk.title}`,
    '',
    `**Page range:** ${chunk.pageRange}`,
    `**Boundary type:** ${chunk.boundaryType}`,
    '',
    '> **Fallback:** this document page was generated by deterministic fallback because the LLM did not produce content.',
    '',
    chunk.content,
    '',
    '## Citations',
    '',
    ...sourceCitations,
    '',
    '## Related',
    '',
    ...wikilinks.map((link) => `- [[${link}]]`),
  ];

  return { frontmatter, body: bodyLines.join('\n') };
}

export function writeDocumentPage(
  filePath: string,
  chunk: Chunk,
  config: Config,
  entityTitles: string[] = [],
  topicTitles: string[] = [],
  llmContent?: LlmPageContent,
): void {
  const content = llmContent
    ? mergeLlmContentWithChunk(llmContent, chunk, config)
    : buildDocumentPage(chunk, config, entityTitles, topicTitles);

  const now = new Date().toISOString();
  const created = readCreatedTimestamp(filePath) ?? (content.frontmatter.created as string | undefined) ?? now;
  content.frontmatter.created = created;
  content.frontmatter.updated = now;

  const full = matter.stringify(content.body, content.frontmatter);
  writeFileSync(filePath, full);
}

function mergeLlmContentWithChunk(
  llmContent: LlmPageContent,
  chunk: Chunk,
  config: Config,
): LlmPageContent {
  const frontmatter = { ...llmContent.frontmatter };
  // Ensure required deterministic fields are present even if the LLM omitted them.
  frontmatter.title = frontmatter.title ?? chunk.title;
  frontmatter.type = 'document';
  frontmatter.wiki = config.wiki.slug;
  frontmatter.tags = Array.isArray(frontmatter.tags) ? frontmatter.tags : chunk.tags;
  frontmatter.confidence = frontmatter.confidence ?? deriveConfidence(chunk);
  frontmatter.below_min = chunk.belowMin;
  frontmatter.char_count = chunk.charCount;
  frontmatter.boundary_type = chunk.boundaryType;
  frontmatter.sources = Array.isArray(frontmatter.sources) && frontmatter.sources.length > 0
    ? frontmatter.sources
    : chunk.sources.map((source) => ({
        id: source.id,
        file: source.file,
        pages: source.pages,
        extracted: source.extracted,
        label: humanizeLabel(pathBasename(source.file)),
      }));

  let body = llmContent.body;
  return { frontmatter, body };
}

function deriveConfidence(chunk: Chunk): 'high' | 'medium' | 'low' {
  if (chunk.belowMin) return 'low';
  if (chunk.boundaryType === 'section' || chunk.boundaryType === 'page') return 'high';
  return 'medium';
}

function pathBasename(filePath: string): string {
  return filePath.split(/[\\/]/).pop() || filePath;
}
